const utf8ByteLength = (value: string) => new TextEncoder().encode(value).length

const uniqueNonEmpty = (values: Array<string | null | undefined>) =>
  values.filter((value, index, array): value is string => {
    if (typeof value !== 'string') return false

    const trimmed = value.trim()
    return trimmed.length > 0 && array.indexOf(value) === index
  })

const basename = (value: string) => {
  const segments = value.split('/')
  return segments[segments.length - 1] ?? value
}

export type RunIssueCategory =
  | 'warning'
  | 'invalid-highlight-uuid'
  | 'managed-page-identity-conflict'
  | 'duplicate-reader-id'
  | 'path-too-long'
  | 'generic'

const NON_BLOCKING_READER_SYNC_RUN_ISSUE_CATEGORIES = new Set<RunIssueCategory>([
  'warning',
  'invalid-highlight-uuid',
  'managed-page-identity-conflict',
  'duplicate-reader-id',
  'path-too-long',
])

export interface RunIssue {
  book: string
  message: string
  category?: RunIssueCategory
  summary?: string
  suggestedAction?: string
  debugFacts?: string[]
  readerDocumentId?: string | null
  namespacePrefix?: string | null
  pageName?: string | null
  userBookId?: number | null
}

export interface DiagnosedRunIssue extends RunIssue {
  category: RunIssueCategory
  summary: string
  suggestedAction: string
  debugFacts: string[]
}

export interface RunIssueBundleContext {
  modeLabel: string
  namespacePrefix: string | null
  logLevel: string
  statusMessage: string
  startedAt: string | null
  completedAt: string | null
  targetDocuments: number | null
  debugHighlightPageLimit: number | null
  processedItems?: number | null
  issuesCount?: number | null
  stats?: Partial<{
    highlightPagesScanned: number
    highlightsScanned: number
    parentDocumentsIdentified: number
    pagesTargeted: number
    pagesProcessed: number
    createdCount: number
    updatedCount: number
    unchangedCount: number
    renamedCount: number
    fetchHighlightsDurationMs: number
    fetchDocumentsDurationMs: number
    writePagesDurationMs: number
  }>
}

const withContextFacts = (
  facts: Array<string | null | undefined>,
  issue: Pick<
    RunIssue,
    'readerDocumentId' | 'namespacePrefix' | 'pageName' | 'userBookId'
  >,
) =>
  uniqueNonEmpty([
    ...facts,
    issue.readerDocumentId
      ? `readerDocumentId=${issue.readerDocumentId}`
      : null,
    issue.namespacePrefix ? `namespacePrefix=${issue.namespacePrefix}` : null,
    issue.pageName ? `pageName=${issue.pageName}` : null,
    issue.userBookId != null ? `userBookId=${issue.userBookId}` : null,
  ])

export const formatRunIssueCategoryLabel = (category: RunIssueCategory) => {
  switch (category) {
    case 'warning':
      return 'Warning'
    case 'invalid-highlight-uuid':
      return 'Invalid highlight UUID'
    case 'managed-page-identity-conflict':
      return 'Managed page identity conflict'
    case 'duplicate-reader-id':
      return 'Duplicate rw-reader-id'
    case 'path-too-long':
      return 'File name too long'
    default:
      return 'Sync error'
  }
}

export const diagnoseRunIssue = (issue: RunIssue): DiagnosedRunIssue => {
  const invalidUuidMatch = issue.message.match(
    /^([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}) is not a valid UUID string\.?$/i,
  )
  if (invalidUuidMatch) {
    return {
      ...issue,
      category: 'invalid-highlight-uuid',
      summary:
        'The generated highlight block id is not a valid RFC 4122 UUID, so Logseq refuses to create the block.',
      suggestedAction:
        'Retry after upgrading to the UUID compatibility fix. This issue is generated by the plugin, not by the source document title.',
      debugFacts: withContextFacts(
        [`generatedHighlightUuid=${invalidUuidMatch[1] ?? '<unknown>'}`],
        issue,
      ),
    }
  }

  const identityConflictMatch = issue.message.match(
    /^Managed page identity conflict for (.*): existing rw-reader-id=([^,;]+), incoming rw-reader-id=([^;]+)(?:; existing-id pages=\[(.*)\]; incoming-id pages=\[(.*)\])?$/,
  )
  if (identityConflictMatch) {
    return {
      ...issue,
      category: 'managed-page-identity-conflict',
      summary:
        'A managed page with the same title already exists, but it is bound to a different Reader document id.',
      suggestedAction:
        'Inspect the existing page and decide which Reader document should own that title. Then rename, archive, or clear the stale page before rerunning sync.',
      debugFacts: withContextFacts(
        [
          `managedPageName=${identityConflictMatch[1] ?? '<unknown>'}`,
          `existingReaderDocumentId=${identityConflictMatch[2] ?? '<unknown>'}`,
          `incomingReaderDocumentId=${identityConflictMatch[3] ?? '<unknown>'}`,
          identityConflictMatch[4]
            ? `existingReaderDocumentPages=${identityConflictMatch[4]}`
            : null,
          identityConflictMatch[5]
            ? `incomingReaderDocumentPages=${identityConflictMatch[5]}`
            : null,
        ],
        issue,
      ),
    }
  }

  const duplicateReaderIdMatch = issue.message.match(
    /^Multiple managed pages share rw-reader-id=([^:]+): (.+)$/,
  )
  if (duplicateReaderIdMatch) {
    return {
      ...issue,
      category: 'duplicate-reader-id',
      summary:
        'More than one managed page currently claims the same Reader document id, so the plugin cannot determine the canonical target page.',
      suggestedAction:
        'Clear or consolidate the duplicate managed pages so that each rw-reader-id maps to exactly one page.',
      debugFacts: withContextFacts(
        [
          `duplicateReaderDocumentId=${duplicateReaderIdMatch[1] ?? '<unknown>'}`,
          `duplicatePages=${duplicateReaderIdMatch[2] ?? '<unknown>'}`,
        ],
        issue,
      ),
    }
  }

  const pathTooLongMatch = issue.message.match(
    /ENAMETOOLONG: name too long, open '([^']+)'/,
  )
  if (pathTooLongMatch) {
    const path = pathTooLongMatch[1] ?? ''
    const fileName = basename(path)

    return {
      ...issue,
      category: 'path-too-long',
      summary:
        'Logseq attempted to persist this managed page to a file path whose file name exceeds the filesystem limit.',
      suggestedAction:
        'Without changing the stored page name, the plugin cannot bypass this Logseq file-system constraint. Use a shorter stored page key, or switch to an alias-based fallback.',
      debugFacts: withContextFacts(
        [
          `targetPath=${path}`,
          `targetFileName=${fileName}`,
          `targetPathBytes=${utf8ByteLength(path)}`,
          `targetFileNameBytes=${utf8ByteLength(fileName)}`,
        ],
        issue,
      ),
    }
  }

  return {
    ...issue,
    category: issue.category ?? 'generic',
    summary:
      issue.summary ??
      'Page sync failed with an unclassified error. The raw message and surrounding run context are included below.',
    suggestedAction:
      issue.suggestedAction ??
      'Copy this issue bundle, set log level to debug if needed, and inspect the console payload for the failing page.',
    debugFacts: withContextFacts(issue.debugFacts ?? [], issue),
  }
}

export const shouldRunIssueBlockReaderSyncCursor = (
  issue: RunIssue | DiagnosedRunIssue,
) => {
  const category = diagnoseRunIssue(issue).category
  return !NON_BLOCKING_READER_SYNC_RUN_ISSUE_CATEGORIES.has(category)
}

export const summarizeRunIssueCategories = (issues: RunIssue[]) => {
  const diagnosedIssues = issues.map((issue) => diagnoseRunIssue(issue))
  const counts = diagnosedIssues.reduce<Record<RunIssueCategory, number>>(
    (accumulator, issue) => {
      accumulator[issue.category] = (accumulator[issue.category] ?? 0) + 1
      return accumulator
    },
    {
      warning: 0,
      'invalid-highlight-uuid': 0,
      'managed-page-identity-conflict': 0,
      'duplicate-reader-id': 0,
      'path-too-long': 0,
      generic: 0,
    },
  )

  return Object.entries(counts)
    .filter(([, count]) => count > 0)
    .map(
      ([category, count]) =>
        `${count} ${formatRunIssueCategoryLabel(category as RunIssueCategory)}`,
    )
    .join(' · ')
}

export const buildRunIssuesBundle = ({
  issues,
  context,
}: {
  issues: RunIssue[]
  context: RunIssueBundleContext | null
}) => {
  const diagnosedIssues = issues.map((issue) => diagnoseRunIssue(issue))
  const categorySummary = summarizeRunIssueCategories(diagnosedIssues)
  const statsEntries = Object.entries(context?.stats ?? {}).filter(
    ([, value]) => value != null,
  )

  return [
    'Readwise Reader Sync Issue Bundle',
    context?.modeLabel ? `Mode: ${context.modeLabel}` : null,
    context?.namespacePrefix ? `Namespace: ${context.namespacePrefix}` : null,
    context?.logLevel ? `Log Level: ${context.logLevel}` : null,
    context?.startedAt ? `Started At: ${context.startedAt}` : null,
    context?.completedAt ? `Completed At: ${context.completedAt}` : null,
    context?.targetDocuments != null
      ? `Target Documents: ${context.targetDocuments}`
      : null,
    context?.debugHighlightPageLimit != null
      ? `Debug Highlight Page Limit: ${context.debugHighlightPageLimit}`
      : null,
    context?.processedItems != null
      ? `Processed Items: ${context.processedItems}`
      : null,
    context?.issuesCount != null ? `Issue Count: ${context.issuesCount}` : null,
    categorySummary ? `Issue Categories: ${categorySummary}` : null,
    context?.statusMessage ? `Status Message: ${context.statusMessage}` : null,
    statsEntries.length > 0 ? '' : null,
    statsEntries.length > 0 ? 'Run Stats:' : null,
    ...statsEntries.map(([key, value]) => `- ${key}: ${value}`),
    '',
    'Issues:',
    ...diagnosedIssues.flatMap((issue, index) => [
      `${index + 1}. ${issue.book}`,
      `   Category: ${formatRunIssueCategoryLabel(issue.category)}`,
      `   Summary: ${issue.summary}`,
      `   Suggested Action: ${issue.suggestedAction}`,
      `   Raw Message: ${issue.message}`,
      ...(issue.debugFacts.length > 0
        ? ['   Debug Facts:', ...issue.debugFacts.map((fact) => `   - ${fact}`)]
        : []),
      '',
    ]),
  ]
    .filter((line): line is string => typeof line === 'string')
    .join('\n')
}
